import { Serie } from './Serie.js';
export var data = [
    new Serie(1, "Breaking Bad", "AMC", 5, "https://i.imgur.com/GGje0vc.jpg", "Set and filmed in Albuquerque, New Mexico, the series tells the story of Walter White, a struggling and depressed high school chemistry teacher who is diagnosed with lung cancer", "https://www.amc.com/shows/breaking-bad"),
    new Serie(2, "Orange Is the New Black", "Netflix", 6, "https://i.imgur.com/EvKe48G.jpg", "The series begins revolving around Piper Chapman, a woman in her thirties living in New York City who is sentenced to 15 months in Litchfield Penitentiary", "https://www.netflix.com/co/title/70242311"),
    new Serie(3, "Game of Thrones", "HBO", 7, "https://i.imgur.com/TDCEV1S.jpg", "American fantasy drama", "https://www.hbo.com/game-of-thrones"),
    new Serie(4, "The Big Bang Theory", "CBS", 12, "https://i.imgur.com/uAEpVWk.jpg", "Leonard and Sheldon are brilliant physicists—geniuses in the laboratory but socially challenged everywhere else. Enter beautiful, street-smart neighbor Penny, who aims to teach them a thing or two about life. Despite their on-again, off-again relationship in the past, Leonard and Penny have finally gotten married. Even Sheldon has found a female companion, entering into a relationship agreement with neurobiologist Amy Farrah Fowler, and he recently took their relationship to the next level by marrying her after a long courtship. In their free time, Leonard and Sheldon enjoy fantasy role-playing games with their ever-expanding universe of friends, including fellow scientists Koothrappali, Wolowitz, and Wolowitz’s adorable microbiologist wife, Bernadette, who is adjusting to life with their two children.", "https://www.cbs.com/shows/big_bang_theory/about/"),
    new Serie(5, "Sherlock", "BBC", 4, "https://i.imgur.com/02B7qhj.jpg", "Sherlock depicts consulting detective Sherlock Holmes (Benedict Cumberbatch) solving various mysteries in modern-day London. Holmes is assisted by his flatmate and friend, Dr John Watson (Martin Freeman), who has returned from military service in Afghanistan with the Royal Army Medical Corps", "https://www.bbc.co.uk/programmes/b018ttws"),
    new Serie(6, "A Very English Scandal", "BBC", 2, "https://i.imgur.com/D4y3DrQ.jpg", "A Very English Scandal is a fact-based three-part British television comedy-drama miniseries based on John Preston's book of the same name.", "https://www.bbc.co.uk/programmes/p065smy4"),
];
